---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php support for apache packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update CentOS repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 and php libraries on CentOS package

    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
