---

- hosts: all
  become: true
  pre_tasks:


  - name: update repo cache (CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache ( Ubuntu)
    tags: always
    apt:
      update_cache: true
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  tasks:


  - name: add ssh key for user simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB0Ig4uWOUNilIY9bnfWVWBxQnrBIS9xye9xQXCIsYFZ ansible"

 
- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

      #- name: install terraform
      #unarchive:
            #src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
            #src: https://releases.hashicorp.com/terraform/1.5.2/terraform_1.5.2_linux_arm64.zip
            #dest: /usr/local/bin
            #remote_src: yes
            #mode: 0755
            #owner: root
            #group: root
 
- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php Ubuntu packages
    tags: apache,pache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install apache2 and php libraries on CentOS package
    tags: apache,httpd,centos
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: changeserver admin email address in config file
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin someguy@serveradminssomewhere.com
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: db,mariadb,centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
        

- hosts: file_servers
  become: true
  tasks:

  - name: install Samba package (target all)
    tags: samba
    package:
      name: samba
      state: latest
